### ISSUE TITLE
can you start an npm package for PDF flipbook lib

### ISSUE THREAD

**Issue by manhydrofire** [HiIamChaitanya/pdf-flipbook#1]
can you start an npm package for flip book lib and pls can you link any documentation to follow for this
thanks

**Comment by HiIamChaitanya** [comment]
yea sure, [documentation link](https://dearflip.com/examples/jquery/index.html) I have made some changes to some lib files

**Comment by HiIamChaitanya** [comment]
if you want you can use some other packages the are also works fine, you can check this as well [https://www.npmjs.com/package/flip-book](https://www.npmjs.com/package/flip-book)
